create table public.products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  name text,
  description text,
  price numeric,
  category text,
  image_url text,
  stock_quantity integer
);